name: Security checker


on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
 
  build:
   
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3 
      
      - name: Check PHP Version
        run: php -v  
      
      - name: Download php security checker
        run: wget https://github.com/fabpot/local-php-security-checker/releases/download/v2.0.4/local-php-security-checker_2.0.4_linux_amd64
        
      - name: List files
        run: ls -l -a 
        
      - name: Rename file
        run: mv local-php-security-checker_2.0.4_linux_amd64 local-php-security-checker  
        
      - name: Change file permission
        run: chmod 0755 local-php-security-checker
      
      - name: List files
        run: ls -l -a
        
      - name: Run security check
        run:  local-php-security-checker --path=./composer.lock --format=json
